geoip.geolocation:
  type: config_object
  label: 'GeoIP locator plugin settings'
  mapping:
    plugin_id:
      type: string
      label: 'Plugin ID of geolocator to use.'
    debug:
      type: boolean
      label: 'Run in debug mode.'
