<?php

/**
 * @file
 * Contains awf_taxonomy_migration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;

/**
 * Implements hook_help().
 */
function awf_taxonomy_migration_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the awf_taxonomy_migration module.
    case 'help.page.awf_taxonomy_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('AWF Taxonomy Vocabularies and Terms Migration.') . '</p>';
      return $output;

    default:
  }
}
